### ISSUE TITLE
We need mysql-shell as a resource

### ISSUE THREAD

**Issue by Abuelodelanada** [canonical/mysql-operator#13]
As we can see in the [OpenStack charm](https://jaas.ai/mysql-innodb-cluster/3), the use `mysql-shell` as a resource to configure the cluster

**Comment by justinmclark** [comment]
Since the linked charm is not a K8s charm, it can install snap packages during the `install` hook. With K8s charms, we probably need to just find (or create) a container image that has everything we need.

**Comment by Abuelodelanada** [comment]
This mysql image has `mysql-shell` installed, we do not need to install it!

https://hub.docker.com/r/mysql/mysql-server/dockerfile
