### ISSUE TITLE
Unit considered unreachable will trigger a workload reset

### ISSUE THREAD

**Issue by phvalguima** [canonical/mysql-operator#241]
Checking the mysql operator, I've noticed that if a given unit is unreachable and fails to be restarted, the charm [will trigger a workload reset](https://github.com/canonical/mysql-operator/blob/main/src/charm.py#L305-L313) and will remove the data from that unit.

Units being unreachable can be caused by network faults or partitions between the cluster (i.e. external factors) and erasing the data will not resolve the issue and put more pressure in the network as data needs to be replicated again.

I'd recommend instead we set the unit into blocked status and inform that a manual intervention is necessary for this unit.

**Comment by shayancanonical** [comment]
With the close of DPE-2214, we are no longer resetting the workload when recovery from unreachable state (by restarting the charmed-mysql mysqld snap service) is unsuccessful. Instead, we are moving the unit into BlockedStatus. The resolution steps for the admin will depend on the cluster status -> this will have to be finessed over time
