### ISSUE TITLE
Add timeout to `action.wait()` in integration tests

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-operator#278]
Example: https://github.com/canonical/mysql-operator/blob/f5fd906b31ca0df2568ccae9c2291c38151470df/tests/integration/test_backups.py#L174

Normally takes a few seconds, but takes ~40 minutes if it fails ([example](https://github.com/canonical/mysql-operator/actions/runs/5784448590/job/15677071283?pr=276#step:14:175))

**Comment by paulomach** [comment]
No longer topical
