### ISSUE TITLE
Add support to Jammy

### ISSUE THREAD

**Issue by paulomach** [canonical/mysql-operator#31]
### Bug Description

Charm does not support jammy

### To Reproduce

n/a

### Environment

n/a

### Relevant log output

```shell
n/a
```

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical  should this issue be resolved in light of https://github.com/canonical/mysql-operator/commit/ef318cc ?
Tnx!

**Comment by taurus-forever** [comment]
> The charm now supports jammy but we're no longer releasing focal—is that an issue?

IMHO, supporting series in parallel is necessary for subordinate charms only.
I have touched this topic in https://github.com/canonical/mysql-operator/issues/22#issuecomment-1398380953
