### ISSUE TITLE
Possible race condition in `_on_start`

### ISSUE THREAD

**Issue by mthaddon** [canonical/mysql-operator#318]
## Steps to reproduce
I'm not sure this is entirely reproducible since it's a race condition. In some circumstances during the `_on_start` method the charm can error trying to query the mysql version because in the meantime it's been restarted and not quite come back up yet.

In a deployed environment we saw it running the configure_mysql_users command okay, but then failin on getting the workload version.

I saw this in the logs: 
```
2023-08-29T13:33:54.378870Z 10 [System] [MY-011086] [Server] Received RESTART from user serverconfig.  Restarting mysqld (Version: 8.0.33-0ubuntu0.22.04.4).
```
So something is restarting it at the same time as we're trying to query the workload version.

https://pastebin.canonical.com/p/N3Yb49KxKR/ is the full mysql daemon log

https://pastebin.canonical.com/p/PVBxbgk77Y/ shows the timing clash

According to @shayancanonical "when we configure instance for innodb, the server is asynchronously restarted to take into effect configuration changes. these logs were super helpful -> i think we will need to think of a way to ensure that mysqld is indeed up and not being restarted when we move on to getting the workload version"

This is on juju 2.9.44 with revision 189 of the machine charm.

**Comment by taurus-forever** [comment]
Just for the history, I cannot reproduce it locally: https://pastebin.canonical.com/p/s5tVDyWVzv/

@shayancanonical : agreed, the existence of the socket file does not indicate that the port is open.

To be improved. Tnx for reporting!

**Comment by paulomach** [comment]
Done on pr #321
