### ISSUE TITLE
Improve user feedback when install goes wrong

### ISSUE THREAD

**Issue by paulomach** [canonical/mysql-operator#34]
### Bug Description

This [error](https://github.com/canonical/mysql-operator/blob/f315762ec328d4f3093c2412822fbaefdd623dd1/src/charm.py#L85) message isn't super helpful, is it not possible to see why the install went wrong and give an indication to the user?

### To Reproduce

n/a

### Environment

n/a

### Relevant log output

```shell
n/a
```

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical I think this issue is no longer topical after merging https://github.com/canonical/mysql-operator/pull/86
Please close this issue if it is true. Tnx!

**Comment by taurus-forever** [comment]
> @taurus-forever The error message is the same after merging #86

Yes, you are right about the error message. We have changed the concept.
Before https://github.com/canonical/mysql-operator/pull/86 users have to trace the issue manually, after https://github.com/canonical/mysql-operator/pull/86 charm is going to re-try installation stage.

Do you have ideas how to improve the final error message after the last re-try (keeping in mind juju 2.9.38 status truncating logic: https://bugs.launchpad.net/juju/+bug/1995470 ? 
IMHO, we should write proper ERROR and DEBUG messages in log, so `juju debug-log` will be the answer about the problem and not unit/app status. What do you think?

**Comment by taurus-forever** [comment]
> We already have more specific messages in the log.

Excellent. IMHO, we can resolve this as the main usability issue were lack if re-try. Resolved.

@paulomach feel free to reopen it if necessary.
