### ISSUE TITLE
Deployment failed on MAAS: Cannot use host 'fun-tick.maas' for instance 'fun-tick.maas:3306' because it resolves to an IP address (127.0.1.1).

### ISSUE THREAD

**Issue by xtrusia** [canonical/mysql-operator#366]
## Steps to reproduce

1.  I faced this issue just when I deploy mysql in maas based environment.

## Expected behavior

deployed well

## Actual behavior

Failed to configure instance for InnoDB

## Versions

Operating system: 

Juju CLI: 2.9.42

Juju agent: 2.9.42

Charm revision: 8.0/stable 196, 8.0/edge 203

LXD: 

## Log output

Juju debug log: 

2023-12-07 02:01:52 ERROR unit.mysql/0.juju-log server.go:316 Failed to configure instance: node-21.maas with error b'Configuring local MySQL instance listening at port 3306 for use in an InnoDB cluster...\n\nThis instance reports its own address as \x1b[1mnode-21.maas:3306\x1b[0m\n\x1b[31mERROR: \x1b[0mCannot use host \'node-21.maas\' for instance \'node-21.maas:3306\' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported. Change your system settings and/or set the MySQL server \'report_host\' variable to a hostname that resolves to a supported IP address.\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nRuntimeError: Dba.configure_instance: Invalid host/IP \'node-21.maas\' resolves to \'127.0.1.1\' which is not supported.\n\n'
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 605, in _run_mysqlsh_script
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysqlsh', '--no-wizard', '--python', '-f', '/var/snap/charmed-mysql/common/tmppskk1yxg']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 1156, in configure_instance
    self._run_mysqlsh_script("\n".join(configure_instance_command))
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 609, in _run_mysqlsh_script
    raise MySQLClientError(e.stderr)
charms.mysql.v0.mysql.MySQLClientError: b'Configuring local MySQL instance listening at port 3306 for use in an InnoDB cluster...\n\nThis instance reports its own address as \x1b[1mnode-21.maas:3306\x1b[0m\n\x1b[31mERROR: \x1b[0mCannot use host \'node-21.maas\' for instance \'node-21.maas:3306\' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported. Change your system settings and/or set the MySQL server \'report_host\' variable to a hostname that resolves to a supported IP address.\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nRuntimeError: Dba.configure_instance: Invalid host/IP \'node-21.maas\' resolves to \'127.0.1.1\' which is not supported.\n\n'

**Comment by taurus-forever** [comment]
@paulomach please comment it: `... Cannot use host 'node-21.maas' for instance 'node-21.maas:3306' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported ...`

**Comment by paulomach** [comment]
> @paulomach please comment it: `... Cannot use host 'node-21.maas' for instance 'node-21.maas:3306' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported ...`

This was solved in the past, but I thinks there's a regression on the ip observer machinery not addressing `127.0.1.1` being present in `/etc/hosts` of ubuntu images.

@xtrusia , can you just confirm that there's a line like:
```
127.0.1.1   node-21
```
on these machines `/etc/hosts` file?

**Comment by xtrusia** [comment]
> > @paulomach please comment it: `... Cannot use host 'node-21.maas' for instance 'node-21.maas:3306' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported ...`
> 
> This was solved in the past, but I thinks there's a regression on the ip observer machinery not addressing `127.0.1.1` being present in `/etc/hosts` of ubuntu images.
> 
> @xtrusia , can you just confirm that there's a line like:
> 
> ```
> 127.0.1.1   node-21
> ```
> 
> on these machines `/etc/hosts` file?

I redeployed it with node-20 please refer to below hosts file

# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
127.0.1.1 node-20.maas node-20
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

10.0.0.210 node-20.maas node-20 # unit=mysql/0

**Comment by paulomach** [comment]
Thank you @xtrusia , as a workaround, if you remove the line:
```
127.0.1.1 node-20.maas node-20
```
the charm should be able to bootstrap.

**Comment by nobuto-m** [comment]
Is there a plan to fix this?

Long story, short, `juju deploy mysql --channel 8.0/edge --base ubuntu@22.04` simply fails with MAAS provider, and logging into each node and update `/etc/hosts` is not a sustainable workaround to me.

```
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 1125, in configure_instance
    self._run_mysqlsh_script("\n".join(configure_instance_command))
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 659, in _run_mysqlsh_script
    raise MySQLClientError(e.stderr)
charms.mysql.v0.mysql.MySQLClientError: b'Configuring local MySQL instance listening at port 3306 for use in an InnoDB cluster...\n\nThis instance reports its own address as \x1b[1mfun-tick.maas:3306\x1b[0m\n\x1b[31mERROR: \x1b[0mCannot use host \'fun-tick.maas\' for instance \'fun-tick.maas:3306\' because it resolves to an IP address (127.0.1.1) that does not match a real network interface, thus it is not supported. Change your system settings and/or set the MySQL server \'report_host\' variable to a hostname that resolves to a supported IP address.\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\nRuntimeError: Dba.configure_instance: Invalid host/IP \'fun-tick.maas\' resolves to \'127.0.1.1\' which is not supported.\n\n'
```

```
$ grep . /etc/hostname /etc/hosts
/etc/hostname:fun-tick
/etc/hosts:# Your system has configured 'manage_etc_hosts' as True.
/etc/hosts:# As a result, if you wish for changes to this file to persist
/etc/hosts:# then you will need to either
/etc/hosts:# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
/etc/hosts:# b.) change or remove the value of 'manage_etc_hosts' in
/etc/hosts:#     /etc/cloud/cloud.cfg or cloud-config from user-data
/etc/hosts:#
/etc/hosts:127.0.1.1 fun-tick.maas fun-tick
/etc/hosts:127.0.0.1 localhost
/etc/hosts:# The following lines are desirable for IPv6 capable hosts
/etc/hosts:::1 localhost ip6-localhost ip6-loopback
/etc/hosts:ff02::1 ip6-allnodes
/etc/hosts:ff02::2 ip6-allrouters
/etc/hosts:192.168.151.114 fun-tick.maas fun-tick # unit=mysql/0
```

**Comment by jeffreychang911** [comment]
SolQA bumped into this issue as well, when deploying mysql 8.0/candidate or edge to maas_cloud.

**Comment by paulomach** [comment]
@xtrusia , fix on release 232 available on channel `8.0/beta`

**Comment by jeffreychang911** [comment]
@taurus-forever @paulomach SolQA saw this again with juju 3.4.6 candidate in this test run, https://solutions.qa.canonical.com/testruns/ab51fdf2-cda3-47fa-a4bd-02ab516002d8
crashdump here - https://oil-jenkins.canonical.com/artifacts/ab51fdf2-cda3-47fa-a4bd-02ab516002d8/generated/generated/mysql/crashdump-2024-09-16-06.10.01.tar.gz
with mysql charm on 8.0/edge, revision 286.

We see same "Failed to configure instance for InnoDB" from juju status, and same stacktrace from debug-log.

However, our lab is offline at this moment due to data center migration.
Would you be able to double check this?

**Comment by paulomach** [comment]
Hi @jeffreychang911 , I'll take a look at the logs to the best that I can

**Comment by paulomach** [comment]
@jeffreychang911 , I don't think it's the same issue, though it's not clear due the logging on the failed step is not rich enough. 
Still not a solution, but I've added [a ticket](https://warthogs.atlassian.net/browse/DPE-5474) to improve the logging there.
