### ISSUE TITLE
Strange Breakage in Vsphere Deployments

### ISSUE THREAD

**Issue by jamesbeedy** [canonical/mysql-operator#433]
New bug for the same issue: https://github.com/canonical/mysql-operator/issues/162

**Comment by taurus-forever** [comment]
Hi @jamesbeedy , thank you to the bugreport.
It looks identical to the several other bugreports we are trying to cover in https://github.com/canonical/mysql-operator/pull/441 (TL;DR: stop relying on hostname which can be affected by user conflicting changes in /etc/host).
If you want to give it an early try, ping @paulomach directly. Tnx!

**Comment by paulomach** [comment]
@jamesbeedy , fix on release 232 available on channel `8.0/beta`
