### ISSUE TITLE
Silent missing required config parameters when using legacy mysql relation

### ISSUE THREAD

**Issue by gustavosr98** [canonical/mysql-operator#55]
### Bug Description

I assumed the user and database creation on mysql relation interface would be triggered by the event of adding a relation to the charm.
I created a Juju CRM and waited for quite some time until I realized the relation was stuck and no data was being exchanged through the relation.

The view on consumer side seems like Mysql charm is still executing something
```
wordpress-k8s/0*  waiting   idle                           Waiting for MySQL relation to become available
```

I just realized [after taking a look at the source code that nothing will happen until I configure the parameters](https://github.com/canonical/mysql-operator/blob/fd6dbb6d75e29fcdbbb433510e4cf2b47b6df54c/src/relations/mysql.py#L110), since there is no default value for them.

It would be useful to add a message to show on juju status output or some add some log lines to tell the user what is happening.

### To Reproduce

```
# Deploy Mysql
juju add-model databases
juju deploy mysql --channel=latest/edge
juju expose mysql

juju run -m aws-controller:databases -u mysql/leader 'open-port 3306/tcp' # [1]
juju offer mysql:mysql mysql

juju add-model infra-microk8s
juju deploy -m aws-controller:infra-microk8s microk8s --channel=latest/stable --config addons="storage dns ingress" --config channel="1.25/stable"
juju expose microk8s

mkdir -p ~/.kube
juju run-action --wait microk8s/leader kubeconfig
juju scp microk8s/leader:config ~/.kube/config
juju add-k8s aws-microk8s --client
juju bootstrap aws-microk8s aws-microk8s

juju add-model apps
juju deploy wordpress-k8s --channel=latest/stable
# Add relation to Mysql on legacy endpoint
juju consume aws-controller:admin/databases.mysql mysql
juju add-relation wordpress-k8s mysql 
```

> I don't think it has to be a juju CRM or to specific use this k8s charm to test the legacy relation. This is just for context as to how I hit the issue.

[1] #53 

### Environment

Cloud: AWS
Juju: 2.9.34 (Client and Controller)
Mysql charm: latest/edge (rev 80)

Cloud: Microk8s v1.25/stable
Juju: 2.9.34 (Client and Controller)
Wordpress-k8s charm: latest/stable (rev 5)

```
$ juju status
[..]
wordpress-k8s/0*  waiting   idle                           Waiting for MySQL relation to become available
```

### Relevant log output

```shell
n/a
```

**Comment by taurus-forever** [comment]
Hi, it will be addressed for [VM](https://warthogs.atlassian.net/browse/DPE-1511) and [K8s](https://warthogs.atlassian.net/browse/DPE-1512). Thank you for reporting!
P.S. we will generate necessary values automatically if they are not pre-defined by peer/user(config).

**Comment by shayancanonical** [comment]
Closing as we believe that the issue to be resolved. Please reopen if this is not the case
