### ISSUE TITLE
database-relation-broken hook fails with error

### ISSUE THREAD

**Issue by wolsen** [canonical/mysql-operator#66]
Charm goes into a blocked state when removing a consuming application or relation. The database-relation-broken hook gets the following traceback as it assumes that the data is available in the relation at this point (it isn't).

unit-mysql-k8s-0: 19:59:42 DEBUG unit.mysql-k8s/0.juju-log database:2: Using local storage: /var/lib/juju/agents/unit-mysql-k8s-0/charm/.unit-state.db already exists
unit-keystone-operator-0: 19:59:42 ERROR juju.worker.uniter pebble poll failed for container "keystone": failed to get pebble info: cannot obtain system details: cannot communicate with server: Get "http://localhost/v1/system-info": dial unix /charm/containers/keystone/pebble.socket: connect: no such file or directory
unit-mysql-k8s-0: 19:59:42 DEBUG unit.mysql-k8s/0.juju-log database:2: new_auth_plugin: caching_sha2_password
unit-mysql-k8s-0: 19:59:42 DEBUG unit.mysql-k8s/0.juju-log database:2: MySQL Provider is available
unit-mysql-k8s-0: 19:59:42 DEBUG unit.mysql-k8s/0.juju-log database:2: Emitting Juju event database_relation_broken.
unit-mysql-k8s-0: 19:59:42 ERROR unit.mysql-k8s/0.juju-log database:2: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 284, in <module>
    main(MySQLCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 409, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/venv/ops/framework.py", line 769, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-0/charm/src/mysqlprovider.py", line 89, in _on_database_relation_broken
    databases = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
unit-mysql-k8s-0: 19:59:42 ERROR juju.worker.uniter.operation hook "database-relation-broken" (via hook dispatching script: dispatch) failed: exit status 1
^C

**Comment by Abuelodelanada** [comment]
Hello @wolsen I have a potential fix for this issue and I would like to test it with the same consuming application. What are you using?

**Comment by wolsen** [comment]
> Hello @wolsen I have a potential fix for this issue and I would like to test it with the same consuming application. What are you using?

I've been working on a keystone-operator charm and the changes are primarily local. Is it the fix merged in here? I can give that a go

**Comment by Abuelodelanada** [comment]
Yes, it's in main branch. It's more a work around, we know we have to refactor many parts of this charm
